#!/usr/bin/env bash
set -euo pipefail

thumbnail_dir="${XDG_CACHE_HOME:-$HOME/.cache}/cliphist/thumbnails"

cliphist_list="$(cliphist list)"
if [ -z "$cliphist_list" ]; then
  fuzzel -d --prompt-only "cliphist: please store something first "
  rm -rf "$thumbnail_dir"
  exit 0
fi

mkdir -p "$thumbnail_dir"

thumbnail_script=$(cat <<EOF
/^[0-9]+[[:space:]]<meta http-equiv=/ { next }
match(\$0, /^([0-9]+)[[:space:]](\[\[[[:space:]])?binary.*(jpg|jpeg|png|bmp)/, grp) {
  cliphist_item_id = grp[1]
  ext = grp[3]
  thumbnail_file = cliphist_item_id "." ext
  system("[ -f ${thumbnail_dir}/" thumbnail_file " ] || printf '%s\t' " cliphist_item_id " | cliphist decode > '${thumbnail_dir}/" thumbnail_file "'")
  print \$0 "\0icon\x1f${thumbnail_dir}/" thumbnail_file
  next
}
{ print }
EOF
)

set +e
item="$(
  printf '%s\n' "$cliphist_list" \
    | gawk "$thumbnail_script" \
    | fuzzel -d --placeholder "Search clipboard..." --counter --no-sort --with-nth 2
)"
exit_code=$?
set -e

# fuzzel custom action exit codes:
# custom-1 -> 10
# custom-2 -> 11
# custom-10 -> 19
if [ "$exit_code" -eq 19 ]; then
  confirmation="$(printf 'No\nYes\n' | fuzzel -d --placeholder "Delete history?" --lines 2)"
  if [ "$confirmation" = "Yes" ]; then
    rm -f ~/.cache/cliphist/db
    rm -rf "$thumbnail_dir"
  fi

elif [ "$exit_code" -eq 10 ]; then
  if [ -n "$item" ]; then
    item_id="$(printf '%s\n' "$item" | cut -f1)"
    printf '%s\n' "$item_id" | cliphist delete
    find "$thumbnail_dir" -name "${item_id}.*" -delete
  fi

elif [ "$exit_code" -eq 11 ]; then
  if [ -n "$item" ]; then
    if printf '%s\n' "$item" | grep -q '\[\[ binary data'; then
      printf '%s\n' "$item" | cliphist decode | wl-copy
    else
      new_content="$(printf '%s\n' "$item" | cliphist decode)"
      old_content="$(wl-paste -n 2>/dev/null || true)"

      if [ -z "$old_content" ]; then
        printf '%s' "$new_content" | wl-copy
      else
        printf '%s\n%s' "$old_content" "$new_content" | wl-copy
      fi
    fi
  fi

else
  if [ -n "$item" ]; then
    printf '%s\n' "$item" | cliphist decode | wl-copy
  fi
fi

find "$thumbnail_dir" -type f | while IFS= read -r thumbnail_file; do
  cliphist_item_id="$(basename "${thumbnail_file%.*}")"
  if ! grep -q "^${cliphist_item_id}[[:space:]]\[\[ binary data" <<<"$cliphist_list"; then
    rm -f "$thumbnail_file"
  fi
done
